# Generated by Django 5.2.5 on 2025-08-19 07:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='kra_pin',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z][0-9]{9}[A-Za-z]$', 'KRA PIN must be 11 characters: 1 letter, 9 digits, 1 letter')], verbose_name='KRA PIN'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Emergency Contact Name'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Emergency Contact Phone'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Emergency Contact Relationship'),
        ),
    ]
