# Generated by Django 4.2.20 on 2025-08-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_staff_kra_pin_alter_staff_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='employment_category',
            field=models.CharField(choices=[('LOCUM', 'Locum'), ('CASUAL', 'Casual')], default='CASUAL', max_length=20),
            preserve_default=False,
        ),
    ]
