# Generated by Django 5.2.5 on 2025-09-01 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contract_contractrenewal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='employment_status',
        ),
    ]
