# Generated by Django 5.2.5 on 2025-09-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_staff_employment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='employment_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('TERMINATED', 'Terminated'), ('RENEWED', 'Renewed'), ('PENDING', 'Pending Renewal')], default='ACTIVE', max_length=20, verbose_name='Employment Status'),
        ),
    ]
