# Generated by Django 5.2.5 on 2025-09-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_staff_employment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='employment_status',
            field=models.CharField(choices=[('AWAITING CONTRACT', 'Awaiting Contract'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('TERMINATED', 'Terminated'), ('RENEWED', 'Renewed'), ('PENDING', 'Pending Renewal'), ('INACTIVE', 'Inactive')], default='AWAITING CONTRACT', max_length=20, verbose_name='Employment Status'),
        ),
    ]
