# Generated by Django 5.2.5 on 2025-09-19 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_staff_employment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='position',
            new_name='designation',
        ),
    ]
