# Generated by Django 5.2.5 on 2025-10-01 05:50

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_position_staff_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('PERMANENT', 'Permanent'), ('LOCUM', 'Locum'), ('CASUAL', 'Casual')], default='FIXED', max_length=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=core.models.contract_upload_path),
        ),
        migrations.AlterField(
            model_name='staff',
            name='employment_category',
            field=models.CharField(choices=[('LOCUM', 'Locum'), ('CASUAL', 'Casual'), ('PERMANENT', 'Permanent and Pentionable')], max_length=20),
        ),
    ]
