# Generated by Django 5.2.5 on 2025-10-09 12:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_contract_contract_type_alter_contract_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='unique_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=30, unique=True, verbose_name='Unique ID'),
        ),
    ]
