# Generated by Django 5.2.5 on 2025-10-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_staff_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='unique_id',
            field=models.CharField(editable=False, max_length=30, unique=True, verbose_name='Unique ID'),
        ),
    ]
