# Generated by Django 5.2.5 on 2025-10-23 05:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_staff_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Deduction Name')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentage Cut (%)')),
                ('description', models.TextField(verbose_name='Description')),
                ('deduction_type', models.CharField(choices=[('MANDATORY', 'Mandatory'), ('VOLUNTARY', 'Voluntary'), ('LOAN', 'Loan')], default='MANDATORY', max_length=20, verbose_name='Deduction Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('min_salary_threshold', models.DecimalField(decimal_places=2, default=0, help_text='Deduction only applies if salary is above this amount', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimum Salary Threshold')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum amount to deduct (overrides percentage if set)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximum Deduction Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applies_to_contract_types', models.ManyToManyField(blank=True, related_name='applicable_deductions', to='core.contract', verbose_name='Applies to Contract Types')),
            ],
            options={
                'verbose_name': 'Deduction',
                'verbose_name_plural': 'Deductions',
                'ordering': ['name'],
                'unique_together': {('name', 'percentage')},
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='deductions',
            field=models.ManyToManyField(blank=True, related_name='contracts', to='core.deduction', verbose_name='Deductions'),
        ),
    ]
