# Generated by Django 5.2.5 on 2025-10-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_deduction_contract_deductions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='deductions',
        ),
        migrations.AddField(
            model_name='contract',
            name='optional_deductions',
            field=models.ManyToManyField(blank=True, limit_choices_to={'deduction_type__in': ['VOLUNTARY', 'LOAN']}, related_name='optional_contracts', to='core.deduction', verbose_name='Optional Deductions (Voluntary/Loans)'),
        ),
    ]
