# Generated by Django 5.2.5 on 2025-10-23 08:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_contract_deductions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Benefit Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='contract',
            name='optional_deductions',
        ),
        migrations.CreateModel(
            name='ContractDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Custom Percentage (%)')),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Fixed Amount (KSh)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deduction_overrides', to='core.contract')),
                ('deduction', models.ForeignKey(limit_choices_to={'deduction_type__in': ['VOLUNTARY', 'LOAN']}, on_delete=django.db.models.deletion.CASCADE, to='core.deduction')),
            ],
            options={
                'verbose_name': 'Contract Deduction Override',
                'verbose_name_plural': 'Contract Deduction Overrides',
                'unique_together': {('contract', 'deduction')},
            },
        ),
    ]
