# Generated by Django 5.2.5 on 2025-10-23 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_benefits_remove_contract_optional_deductions_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Benefits',
        ),
        migrations.AlterUniqueTogether(
            name='deduction',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='deduction',
            name='applies_to_contract_types',
        ),
        migrations.DeleteModel(
            name='ContractDeduction',
        ),
        migrations.DeleteModel(
            name='Deduction',
        ),
    ]
