# Generated by Django 5.2.5 on 2025-10-23 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_benefits_alter_deduction_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='kra_pin',
        ),
    ]
