# Generated by Django 5.2.5 on 2025-11-04 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_designation_remove_staff_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
