# Generated by Django 5.2.5 on 2025-11-05 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_contract_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='is_active',
        ),
    ]
