# Generated by Django 5.2.5 on 2025-10-23 18:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0013_delete_benefits_alter_deduction_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Deduction Name')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentage Cut (%)')),
                ('description', models.TextField(verbose_name='Description')),
                ('deduction_type', models.CharField(choices=[('MANDATORY', 'Mandatory'), ('VOLUNTARY', 'Voluntary'), ('LOAN', 'Loan')], default='MANDATORY', max_length=20, verbose_name='Deduction Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('min_salary_threshold', models.DecimalField(decimal_places=2, default=0, help_text='Deduction only applies if salary is above this amount', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimum Salary Threshold')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum amount to deduct (overrides percentage if set)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximum Deduction Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applies_to_contract_types', models.ManyToManyField(blank=True, related_name='applicable_deductions', to='core.contract', verbose_name='Applies to Contract Types')),
            ],
            options={
                'verbose_name': 'Deduction',
                'verbose_name_plural': 'Deductions',
                'ordering': ['name'],
                'unique_together': {('name', 'percentage')},
            },
        ),
        migrations.CreateModel(
            name='ContractDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Custom Percentage (%)')),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Fixed Amount (KSh)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deduction_overrides', to='core.contract')),
                ('deduction', models.ForeignKey(limit_choices_to={'deduction_type__in': ['VOLUNTARY', 'LOAN']}, on_delete=django.db.models.deletion.CASCADE, to='payroll.deduction')),
            ],
            options={
                'verbose_name': 'Contract Deduction Override',
                'verbose_name_plural': 'Contract Deduction Overrides',
                'unique_together': {('contract', 'deduction')},
            },
        ),
    ]
