# Generated by Django 5.2.5 on 2025-11-04 01:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_designation_remove_staff_salary_and_more'),
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payroll',
            options={'ordering': ['-pay_month'], 'verbose_name': 'Payroll', 'verbose_name_plural': 'Payrolls'},
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='payroll',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved At'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payrolls', to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='pay_month',
            field=models.DateField(default=django.utils.timezone.now, help_text='First day of the month that this payslip covers', verbose_name='Pay Month'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payroll',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='pay_period_end',
            field=models.DateField(editable=False, verbose_name='Pay Period End'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='pay_period_start',
            field=models.DateField(editable=False, verbose_name='Pay Period Start'),
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('staff', 'pay_month')},
        ),
    ]
