# Generated by Django 5.2.5 on 2025-10-23 20:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_contract_benefits_remove_staff_kra_pin'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_period_start', models.DateField(verbose_name='Pay Period Start')),
                ('pay_period_end', models.DateField(verbose_name='Pay Period End')),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Gross Salary')),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Deductions')),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Net Salary')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Bank Name')),
                ('bank_branch', models.CharField(max_length=100, verbose_name='Bank Branch')),
                ('bank_branch_code', models.CharField(max_length=20, verbose_name='Bank Branch Code')),
                ('account_no', models.CharField(max_length=20, verbose_name='Account Number')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Generated At')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='payslips/%Y/%m/', verbose_name='Payslip PDF')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_contract', to='core.contract', verbose_name='Contract')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_identity', to='core.staff', verbose_name='Staff')),
            ],
            options={
                'verbose_name': 'Payroll',
                'verbose_name_plural': 'Payrolls',
                'ordering': ['-pay_period_end'],
                'unique_together': {('staff', 'pay_period_start', 'pay_period_end')},
            },
        ),
    ]
