# Generated by Django 5.2.5 on 2025-10-23 20:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='kra_pin',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z][0-9]{9}[A-Za-z]$', 'KRA PIN must be 11 characters: 1 letter, 9 digits, 1 letter')], verbose_name='KRA PIN'),
        ),
    ]
