# Generated by Django 5.2.5 on 2025-11-04 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_payroll_options_alter_payroll_unique_together_and_more'),
    ]

    operations = [
    ]
